# Generated by Django 2.0.6 on 2019-03-10 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_boards_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='cards',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='list_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boards.Lists'),
        ),
    ]
