# Generated by Django 2.0.6 on 2019-03-10 00:59

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190310_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='labels',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), blank=True, null=True, size=10),
        ),
    ]
