# Generated by Django 2.0.6 on 2019-03-10 01:12

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_boards_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boards',
            name='labels',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), blank=True, null=True, size=6),
        ),
    ]
