# Generated by Django 2.0.6 on 2019-03-10 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20190310_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='list_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Lists'),
        ),
    ]
